language: python

services: docker

script:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_USERPASS"
  - docker build --tag compdatasci/spyder-desktop . && docker push compdatasci/spyder-desktop
  - docker images
