language: python

services: docker

script:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_USERPASS"
  - docker build --tag unifem/desktop-base:py3.6.1 . && docker push unifem/desktop-base:py3.6.1
  - docker images
