os: linux
dist: trusty
sudo: required
language: python
services: docker

env:
  - XVFB=1
  - XVFB=0

before_install:
  # Start up xvfb
  - '[[ "$XVFB" != "1" ]] || /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid
     --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16'

before_script:
  - '[[ "$XVFB" != "1" ]] || export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start'

script:
  - docker --version
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_USERPASS"
  # Build only if the commit range of a push contains Dockerfile or .travis.yml
  - '[[ "$TRAVIS_EVENT_TYPE" == "push" && -n "$TRAVIS_COMMIT_RANGE" &&
        -z "$(git diff --name-only $TRAVIS_COMMIT_RANGE |
            grep -e Dockerfile -e .travis.yml)" ]] || [[ "$XVFB" != "1" ]] ||
     (docker build --tag compdatasci/spyder-desktop:3.5.1
                   --tag compdatasci/spyder-desktop:latest . &&
      docker push compdatasci/spyder-desktop &&
      touch success)'
  # Test script without launching webbrowser and push new image if successful
  - './spyder_desktop.py -d -n && docker stop $(docker ps -q)'
  - './spyder_jupyter.py -d -n && docker stop $(docker ps -q)'
  - docker images
